//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetraProductsTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleID { get; set; }
        public string ArticleNumber { get; set; }
        public string ArticleName { get; set; }
        public string Description { get; set; }
        public string ArticleCategory { get; set; }
        public decimal ArticlePrice { get; set; }
    }
}
